services:
  api:
    build:
      context: packages/api
      dockerfile: Dockerfile
      target: development
    environment:
      ENVIRONMENT: "local"
      DB_HOST: "database"
      DB_PORT: 3306
      DB_NAME: "tadashboard"
      DB_USER: "root"
      DB_NAME_TEST: "tadashboard_test"
      TZ: "Asia/Tokyo"
    volumes:
      - ./packages/api:/var/app
      - go_cache:/go
    ports:
      - "4000:4000"
    depends_on:
      - database
    command: /bin/sh -c "go mod tidy && dockerize -timeout 60s -wait tcp://database:3306 && air -c .air.toml"
  database:
    image: mysql:8.0.35
    volumes:
      - ./packages/api/setup_test.sh:/docker-entrypoint-initdb.d/setup.sh
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "tadashboard"
      MYSQL_TEST_DATABASE: "tadashboard_test"
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    user: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --default-authentication-plugin=mysql_native_password
    tty: true

volumes:
  go_cache:
