development:
  dialect: mysql
  dir: db/migrations
  datasource: ${DB_USER}:@tcp(${DB_HOST})/${DB_NAME}?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true&loc=Asia%2FTokyo&time_zone=%27Asia%2FTokyo%27
  table: migrations
